###
GET http://localhost:8082/USD
Accept: application/json

###
GET http://localhost:8082/EUR
Accept: application/json

###
GET http://localhost:8082/GBP
Accept: application/json

###
GET http://localhost:8082/
Accept: application/json